### ISSUE TITLE
OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [Miki18/oop-put-course#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [x] Rename repository to **oop-put-course**
- [x] Rename file to task1.cpp
- [ ] Format code properly
- [x] Don't use polish language
